package com.velox.jewelvault.ui.theme

import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color


val primaryLight = Color(0xFFD0B17D)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDEA8)
val onPrimaryContainerLight = Color(0xFF271900)
val secondaryLight = Color(0xFF6D5C3F)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFF7DFBB)
val onSecondaryContainerLight = Color(0xFF251A04)
val tertiaryLight = Color(0xFF4D6544)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFCFEBC1)
val onTertiaryContainerLight = Color(0xFF0B2006)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFC2621E)//Color(0xFFFFF8F3)
val onBackgroundLight = Color(0xFF201B13)
val surfaceLight = Color(0xFFFFF8EF)
val onSurfaceLight = Color(0xFF1E1B13)
val surfaceVariantLight = Color(0xFFEEE1CF)
val onSurfaceVariantLight = Color(0xFF4E4639)
val outlineLight = Color(0xFF807667)
val outlineVariantLight = Color(0xFFD1C5B4)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF333027)
val inverseOnSurfaceLight = Color(0xFFF7F0E2)
val inversePrimaryLight = Color(0xFFEEBF6D)
val surfaceDimLight = Color(0xFFE0D9CC)
val surfaceBrightLight = Color(0xFFFFF8EF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFAF3E5)
val surfaceContainerLight = Color(0xFFF5EDDF)
val surfaceContainerHighLight = Color(0xFFEFE7DA)
val surfaceContainerHighestLight = Color(0xFFE9E2D4)

val primaryDark = Color(0xFFD0B17D)
val onPrimaryDark = Color(0xFF422D00)
val primaryContainerDark = Color(0xFF5E4200)
val onPrimaryContainerDark = Color(0xFFFFDEA8)
val secondaryDark = Color(0xFFDAC3A0)
val onSecondaryDark = Color(0xFF3C2E15)
val secondaryContainerDark = Color(0xFF54442A)
val onSecondaryContainerDark = Color(0xFFF7DFBB)
val tertiaryDark = Color(0xFFB3CEA6)
val onTertiaryDark = Color(0xFF203619)
val tertiaryContainerDark = Color(0xFF364D2E)
val onTertiaryContainerDark = Color(0xFFCFEBC1)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF17130B)
val onBackgroundDark = Color(0xFFECE1D4)
val surfaceDark = Color(0xFF16130B)
val onSurfaceDark = Color(0xFFE9E2D4)
val surfaceVariantDark = Color(0xFF4E4639)
val onSurfaceVariantDark = Color(0xFFD1C5B4)
val outlineDark = Color(0xFF9A8F80)
val outlineVariantDark = Color(0xFF4E4639)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE9E2D4)
val inverseOnSurfaceDark = Color(0xFF333027)
val inversePrimaryDark = Color(0xFF7B580C)
val surfaceDimDark = Color(0xFF16130B)
val surfaceBrightDark = Color(0xFF3C392F)
val surfaceContainerLowestDark = Color(0xFF100E07)
val surfaceContainerLowDark = Color(0xFF1E1B13)
val surfaceContainerDark = Color(0xFF221F17)
val surfaceContainerHighDark = Color(0xFF2D2A21)
val surfaceContainerHighestDark = Color(0xFF38342B)

/*val primaryLight = Color(0xFF7A573D)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFC09578)
val onPrimaryContainerLight = Color(0xFF4C2E18)
val secondaryLight = Color(0xFF764C2F)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF926445)
val onSecondaryContainerLight = Color(0xFFFFEFE7)
val tertiaryLight = Color(0xFF1F0900)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF3A1D09)
val onTertiaryContainerLight = Color(0xFFAF8267)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF8F5)
val onBackgroundLight = Color(0xFF1F1B19)
val surfaceLight = Color(0xFFFDF8F7)
val onSurfaceLight = Color(0xFF1C1B1B)
val surfaceVariantLight = Color(0xFFF0DFD6)
val onSurfaceVariantLight = Color(0xFF4F453E)
val outlineLight = Color(0xFF81756D)
val outlineVariantLight = Color(0xFFD3C4BA)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF313030)
val inverseOnSurfaceLight = Color(0xFFF4F0EE)
val inversePrimaryLight = Color(0xFFECBD9E)
val surfaceDimLight = Color(0xFFDDD9D8)
val surfaceBrightLight = Color(0xFFFDF8F7)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF7F3F1)
val surfaceContainerLight = Color(0xFFF1EDEC)
val surfaceContainerHighLight = Color(0xFFECE7E6)
val surfaceContainerHighestLight = Color(0xFFE6E2E0)

val primaryLightMediumContrast = Color(0xFF4D2F19)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF8B654B)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF512D13)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF916344)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF1F0900)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF3A1D09)
val onTertiaryContainerLightMediumContrast = Color(0xFFD6A588)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF8F5)
val onBackgroundLightMediumContrast = Color(0xFF1F1B19)
val surfaceLightMediumContrast = Color(0xFFFDF8F7)
val onSurfaceLightMediumContrast = Color(0xFF121111)
val surfaceVariantLightMediumContrast = Color(0xFFF0DFD6)
val onSurfaceVariantLightMediumContrast = Color(0xFF3E342E)
val outlineLightMediumContrast = Color(0xFF5B5049)
val outlineVariantLightMediumContrast = Color(0xFF776B63)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF313030)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF4F0EE)
val inversePrimaryLightMediumContrast = Color(0xFFECBD9E)
val surfaceDimLightMediumContrast = Color(0xFFC9C6C4)
val surfaceBrightLightMediumContrast = Color(0xFFFDF8F7)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF7F3F1)
val surfaceContainerLightMediumContrast = Color(0xFFECE7E6)
val surfaceContainerHighLightMediumContrast = Color(0xFFE0DCDB)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD5D1CF)

val primaryLightHighContrast = Color(0xFF412510)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF63422A)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF452309)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF674024)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF1F0900)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF3A1D09)
val onTertiaryContainerLightHighContrast = Color(0xFFFFD2B8)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF8F5)
val onBackgroundLightHighContrast = Color(0xFF1F1B19)
val surfaceLightHighContrast = Color(0xFFFDF8F7)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFF0DFD6)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF332A24)
val outlineVariantLightHighContrast = Color(0xFF524740)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF313030)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFECBD9E)
val surfaceDimLightHighContrast = Color(0xFFBBB8B7)
val surfaceBrightLightHighContrast = Color(0xFFFDF8F7)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF4F0EE)
val surfaceContainerLightHighContrast = Color(0xFFE6E2E0)
val surfaceContainerHighLightHighContrast = Color(0xFFD8D3D2)
val surfaceContainerHighestLightHighContrast = Color(0xFFC9C6C4)

val primaryDark = Color(0xFFECBD9E)
val onPrimaryDark = Color(0xFF462A14)
val primaryContainerDark = Color(0xFFC09578)
val onPrimaryContainerDark = Color(0xFF4C2E18)
val secondaryDark = Color(0xFFF4BA96)
val onSecondaryDark = Color(0xFF4A280D)
val secondaryContainerDark = Color(0xFF926445)
val onSecondaryContainerDark = Color(0xFFFFEFE7)
val tertiaryDark = Color(0xFFEFBC9E)
val onTertiaryDark = Color(0xFF482914)
val tertiaryContainerDark = Color(0xFF3A1D09)
val onTertiaryContainerDark = Color(0xFFAF8267)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF161311)
val onBackgroundDark = Color(0xFFEAE1DD)
val surfaceDark = Color(0xFF141313)
val onSurfaceDark = Color(0xFFE6E2E0)
val surfaceVariantDark = Color(0xFF4F453E)
val onSurfaceVariantDark = Color(0xFFD3C4BA)
val outlineDark = Color(0xFF9C8E86)
val outlineVariantDark = Color(0xFF4F453E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE6E2E0)
val inverseOnSurfaceDark = Color(0xFF313030)
val inversePrimaryDark = Color(0xFF7A573D)
val surfaceDimDark = Color(0xFF141313)
val surfaceBrightDark = Color(0xFF3A3938)
val surfaceContainerLowestDark = Color(0xFF0F0E0E)
val surfaceContainerLowDark = Color(0xFF1C1B1B)
val surfaceContainerDark = Color(0xFF201F1F)
val surfaceContainerHighDark = Color(0xFF2B2A29)
val surfaceContainerHighestDark = Color(0xFF363434)

val primaryDarkMediumContrast = Color(0xFFFFD4B8)
val onPrimaryDarkMediumContrast = Color(0xFF3A1F0A)
val primaryContainerDarkMediumContrast = Color(0xFFC09578)
val onPrimaryContainerDarkMediumContrast = Color(0xFF200B00)
val secondaryDarkMediumContrast = Color(0xFFFFD4B9)
val onSecondaryDarkMediumContrast = Color(0xFF3D1D04)
val secondaryContainerDarkMediumContrast = Color(0xFFB88664)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFFFD4BB)
val onTertiaryDarkMediumContrast = Color(0xFF3B1E0A)
val tertiaryContainerDarkMediumContrast = Color(0xFFB5876C)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF161311)
val onBackgroundDarkMediumContrast = Color(0xFFEAE1DD)
val surfaceDarkMediumContrast = Color(0xFF141313)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF4F453E)
val onSurfaceVariantDarkMediumContrast = Color(0xFFE9D9D0)
val outlineDarkMediumContrast = Color(0xFFBEAFA6)
val outlineVariantDarkMediumContrast = Color(0xFF9B8E85)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE6E2E0)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2B2A29)
val inversePrimaryDarkMediumContrast = Color(0xFF614129)
val surfaceDimDarkMediumContrast = Color(0xFF141313)
val surfaceBrightDarkMediumContrast = Color(0xFF464443)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF080707)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1E1D1D)
val surfaceContainerDarkMediumContrast = Color(0xFF292827)
val surfaceContainerHighDarkMediumContrast = Color(0xFF343232)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3F3D3D)

val primaryDarkHighContrast = Color(0xFFFFECE2)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFE8B99A)
val onPrimaryContainerDarkHighContrast = Color(0xFF180700)
val secondaryDarkHighContrast = Color(0xFFFFECE3)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFEFB792)
val onSecondaryContainerDarkHighContrast = Color(0xFF180700)
val tertiaryDarkHighContrast = Color(0xFFFFECE3)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFEBB89A)
val onTertiaryContainerDarkHighContrast = Color(0xFF190600)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF161311)
val onBackgroundDarkHighContrast = Color(0xFFEAE1DD)
val surfaceDarkHighContrast = Color(0xFF141313)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF4F453E)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFFEEDE3)
val outlineVariantDarkHighContrast = Color(0xFFCFC0B7)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE6E2E0)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF614129)
val surfaceDimDarkHighContrast = Color(0xFF141313)
val surfaceBrightDarkHighContrast = Color(0xFF51504F)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF201F1F)
val surfaceContainerDarkHighContrast = Color(0xFF313030)
val surfaceContainerHighDarkHighContrast = Color(0xFF3C3B3A)
val surfaceContainerHighestDarkHighContrast = Color(0xFF484646)
*/

//custom color component
val LightGreen = Color(0xFF90EE90)
val LightRed = Color(0xFFF08080)
val Orange = Color(0xFFFFA500)

val GoldBackground = Brush.horizontalGradient(
    colors = listOf(
        Color(0xFFC8A66F),
        primaryLight, // your primary
//        primaryLight, // your primary
        Color(0xFFF8E8AD),
        primaryLight,
    )
)









