package com.velox.jewelvault.utils.sync

object ExcelSchema {
    const val CURRENT_SCHEMA_VERSION = 2

    private val baseHeaders = mapOf(
        "UsersEntity" to listOf("id", "name", "email", "mobileNo", "token", "pin", "role", "lastUpdated"),
        "UserAdditionalInfoEntity" to listOf(
            "userId",
            "aadhaarNumber",
            "address",
            "emergencyContactPerson",
            "emergencyContactNumber",
            "governmentIdNumber",
            "governmentIdType",
            "dateOfBirth",
            "bloodGroup",
            "isActive",
            "createdAt",
            "updatedAt"
        ),
        "StoreEntity" to listOf(
            "storeId",
            "userId",
            "proprietor",
            "name",
            "email",
            "phone",
            "address",
            "registrationNo",
            "gstinNo",
            "panNo",
            "image",
            "invoiceNo",
            "upiId"
        ),
        "CategoryEntity" to listOf("catId", "catName", "gsWt", "fnWt", "userId", "storeId"),
        "SubCategoryEntity" to listOf(
            "subCatId",
            "catId",
            "userId",
            "storeId",
            "catName",
            "subCatName",
            "quantity",
            "gsWt",
            "fnWt"
        ),
        "ItemEntity" to listOf(
            "itemId",
            "itemAddName",
            "catId",
            "userId",
            "storeId",
            "catName",
            "subCatId",
            "subCatName",
            "entryType",
            "quantity",
            "gsWt",
            "ntWt",
            "fnWt",
            "purity",
            "crgType",
            "crg",
            "othCrgDes",
            "othCrg",
            "cgst",
            "sgst",
            "igst",
            "huid",
            "unit",
            "addDesKey",
            "addDesValue",
            "addDate",
            "modifiedDate",
            "sellerFirmId",
            "purchaseOrderId",
            "purchaseItemId"
        ),
        "CustomerEntity" to listOf(
            "mobileNo",
            "name",
            "address",
            "gstin_pan",
            "addDate",
            "lastModifiedDate",
            "totalItemBought",
            "totalAmount",
            "notes",
            "userId",
            "storeId"
        ),
        "CustomerKhataBookPlanEntity" to listOf(
            "planId",
            "name",
            "payMonths",
            "benefitMonths",
            "description",
            "benefitPercentage",
            "userId",
            "storeId",
            "createdAt",
            "updatedAt"
        ),
        "CustomerKhataBookEntity" to listOf(
            "khataBookId",
            "customerMobile",
            "planName",
            "startDate",
            "endDate",
            "monthlyAmount",
            "totalMonths",
            "totalAmount",
            "status",
            "notes",
            "userId",
            "storeId"
        ),
        "CustomerTransactionEntity" to listOf(
            "transactionId",
            "customerMobile",
            "transactionDate",
            "amount",
            "transactionType",
            "category",
            "description",
            "referenceNumber",
            "paymentMethod",
            "khataBookId",
            "monthNumber",
            "notes",
            "userId",
            "storeId"
        ),
        "OrderEntity" to listOf(
            "orderId",
            "customerMobile",
            "storeId",
            "userId",
            "orderDate",
            "totalAmount",
            "totalTax",
            "totalCharge",
            "discount",
            "note"
        ),
        "OrderItemEntity" to listOf(
            "orderItemId",
            "orderId",
            "orderDate",
            "itemId",
            "customerMobile",
            "catId",
            "catName",
            "itemAddName",
            "subCatId",
            "subCatName",
            "entryType",
            "quantity",
            "gsWt",
            "ntWt",
            "fnWt",
            "fnMetalPrice",
            "purity",
            "crgType",
            "crg",
            "othCrgDes",
            "othCrg",
            "cgst",
            "sgst",
            "igst",
            "huid",
            "addDesKey",
            "addDesValue",
            "price",
            "charge",
            "tax",
            "sellerFirmId",
            "purchaseOrderId",
            "purchaseItemId"
        ),
        "ExchangeItemEntity" to listOf(
            "exchangeItemId",
            "orderId",
            "orderDate",
            "customerMobile",
            "metalType",
            "purity",
            "grossWeight",
            "fineWeight",
            "price",
            "isExchangedByMetal",
            "exchangeValue",
            "addDate"
        ),
        "FirmEntity" to listOf("firmId", "firmName", "firmMobileNumber", "gstNumber", "address"),
        "PurchaseOrderEntity" to listOf(
            "purchaseOrderId",
            "sellerId",
            "billNo",
            "billDate",
            "entryDate",
            "extraChargeDescription",
            "extraCharge",
            "totalFinalWeight",
            "totalFinalAmount",
            "notes",
            "cgstPercent",
            "sgstPercent",
            "igstPercent"
        ),
        "PurchaseOrderItemEntity" to listOf(
            "purchaseItemId",
            "purchaseOrderId",
            "catId",
            "catName",
            "subCatId",
            "subCatName",
            "gsWt",
            "purity",
            "ntWt",
            "fnWt",
            "fnRate",
            "wastagePercent"
        ),
        "MetalExchangeEntity" to listOf(
            "exchangeId",
            "purchaseOrderId",
            "catId",
            "catName",
            "subCatId",
            "subCatName",
            "fnWeight"
        )
    )

    val requiredHeadersByVersion: Map<Int, Map<String, List<String>>> = mapOf(
        1 to baseHeaders,
        CURRENT_SCHEMA_VERSION to baseHeaders
    )

    val earliestKnownVersion: Int = requiredHeadersByVersion.keys.minOrNull() ?: 1
}
